#!/bin/bash

# Example usage:
#
# docker/release-docker -h docker.io/istio \
#  -t $(git rev-parse --short HEAD),$(date +%Y%m%d%H%M%S)" \
#  -i "init,init_debug,app,app_debug,runtime,runtime_debug"

function usage() {
  echo "$0 \
    -h <docker image repository> \
    -t <comma separated list of docker image tags> \
    -i <comma separated list of docker images>"
  exit 1
}


while getopts :h:i:t:: arg; do
  case ${arg} in
    h) HUB="${OPTARG}";;
    i) IMAGES="${OPTARG}";;
    t) TAGS="${OPTARG}";;
  esac
done

[[ -z "${HUB}" ]] && usage
[[ -z "${TAGS}" ]] && usage
[[ -z "${IMAGES}" ]] && usage

IFS=',' read -ra TAGS <<< "${TAGS}"
IFS=',' read -ra IMAGES <<< "${IMAGES}"

if [[ "${HUB}" =~ ^gcr\.io ]]; then
    gcloud docker --authorize-only
fi

set -ex

for IMAGE in "${IMAGES[@]}"; do
    for TAG in "${TAGS[@]}"; do
        bazel ${BAZEL_STARTUP_ARGS} run "//docker:${IMAGE}" "${HUB}/${IMAGE}:${TAG}"
        docker push "${HUB}/${IMAGE}:${TAG}"
    done
done
